name: Run Notion to Telegram Service Cron

on:
  schedule:
    - cron: '*/3 * * * *' # Setiap 2 menit jalan
  workflow_dispatch: # Bisa juga manual jalanin

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Create id.json if not exist
      run: |
        if [ ! -f id.json ]; then echo "[]" > id.json; fi

    - name: Download id.json artifact (if exists)
      uses: actions/download-artifact@v4
      with:
        name: id
        path: .
      continue-on-error: true

    - name: Create .env file from GitHub Secrets
      env:
        ENV_VARS: ${{ secrets.env }}
      run: |
        echo "$ENV_VARS" > .env

    - name: Run Python script
      run: |
        python notion_to_telegram.py

    - name: Commit and push updated id.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add id.json
        git commit -m "Update id.json [skip ci]" || echo "No changes to commit"
        git push
