name: Run Notion to Telegram Service Cron

on:
  schedule:
    - cron: '*/3 * * * *'  # Setiap 3 menit
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Buat file .env dari secret
      env:
        ENV_VARS: ${{ secrets.env }}
      run: |
        echo "$ENV_VARS" > .env

    - name: Setup id.json file
      run: |
        echo "${{ secrets.ID_JSON }}" > id.json

    - name: Jalankan script Python
      run: |
        python notion_to_telegram.py
